// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	listLibrary: (filter: CategoryFilter, search: {
	field: LibrarySearchField,
	query: string,
} | null) => typedError<LibraryItem[], CommandError>(__TAURI_INVOKE("list_library", { filter, search })),
	addToLibrary: (sourceId: string, mangaId: string, totalChapters: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("add_to_library", { sourceId, mangaId, totalChapters })),
	addListingToLibrary: (sourceId: string, item: MangaSimple) => typedError<null, CommandError>(__TAURI_INVOKE("add_listing_to_library", { sourceId, item })),
	addMangaToLibrary: (sourceId: string, manga: Manga, totalChapters: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("add_manga_to_library", { sourceId, manga, totalChapters })),
	/**
	 *  Fills the chapter cache for one entry without the progress events a full
	 *  refresh emits — used right after an add whose caller had no chapter count.
	 */
	cacheEntryChapters: (sourceId: string, mangaId: string) => typedError<number, CommandError>(__TAURI_INVOKE("cache_entry_chapters", { sourceId, mangaId })),
	removeFromLibrary: (sourceId: string, mangaId: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_from_library", { sourceId, mangaId })),
	isInLibrary: (sourceId: string, mangaId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("is_in_library", { sourceId, mangaId })),
	listCategories: () => typedError<Category[], CommandError>(__TAURI_INVOKE("list_categories")),
	libraryLockIsSet: () => typedError<boolean, CommandError>(__TAURI_INVOKE("library_lock_is_set")),
	verifyLibraryPassword: (password: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("verify_library_password", { password })),
	setLibraryPassword: (current: string | null, password: string) => typedError<null, CommandError>(__TAURI_INVOKE("set_library_password", { current, password })),
	clearLibraryLock: () => typedError<null, CommandError>(__TAURI_INVOKE("clear_library_lock")),
	createCategory: (name: string) => typedError<Category, CommandError>(__TAURI_INVOKE("create_category", { name })),
	renameCategory: (categoryId: string, name: string) => typedError<null, CommandError>(__TAURI_INVOKE("rename_category", { categoryId, name })),
	updateCategoryOptions: (categoryId: string, options: CategoryOptions) => typedError<null, CommandError>(__TAURI_INVOKE("update_category_options", { categoryId, options })),
	deleteCategory: (categoryId: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_category", { categoryId })),
	reorderCategories: (categoryIds: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("reorder_categories", { categoryIds })),
	categoriesForEntry: (sourceId: string, mangaId: string) => typedError<string[], CommandError>(__TAURI_INVOKE("categories_for_entry", { sourceId, mangaId })),
	setEntryCategories: (sourceId: string, mangaId: string, categoryIds: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("set_entry_categories", { sourceId, mangaId, categoryIds })),
	bulkCategoryCounts: (entries: EntryRef[]) => typedError<CategoryCount[], CommandError>(__TAURI_INVOKE("bulk_category_counts", { entries })),
	bulkUpdateCategories: (entries: EntryRef[], add: string[], remove: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("bulk_update_categories", { entries, add, remove })),
	refreshLibrary: (scope: RefreshScope, force: boolean) => typedError<RefreshSummary, CommandError>(__TAURI_INVOKE("refresh_library", { scope, force })),
	libraryUpdates: (limit: number) => typedError<LibraryUpdate[], CommandError>(__TAURI_INVOKE("library_updates", { limit })),
	clearLibraryUpdates: () => typedError<null, CommandError>(__TAURI_INVOKE("clear_library_updates")),
	continueReading: (limit: number) => typedError<ContinueReadingItem[], CommandError>(__TAURI_INVOKE("continue_reading", { limit })),
	removeHistoryEntries: (entries: HistoryEntryRef[]) => typedError<null, CommandError>(__TAURI_INVOKE("remove_history_entries", { entries })),
	markChapterRead: (sourceId: string, mangaId: string, chapterId: string) => typedError<null, CommandError>(__TAURI_INVOKE("mark_chapter_read", { sourceId, mangaId, chapterId })),
	markChapterUnread: (sourceId: string, mangaId: string, chapterId: string) => typedError<null, CommandError>(__TAURI_INVOKE("mark_chapter_unread", { sourceId, mangaId, chapterId })),
	markChaptersRead: (sourceId: string, mangaId: string, chapterIds: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("mark_chapters_read", { sourceId, mangaId, chapterIds })),
	markChaptersUnread: (sourceId: string, mangaId: string, chapterIds: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("mark_chapters_unread", { sourceId, mangaId, chapterIds })),
	isChapterRead: (sourceId: string, mangaId: string, chapterId: string) => typedError<boolean, CommandError>(__TAURI_INVOKE("is_chapter_read", { sourceId, mangaId, chapterId })),
	readChaptersForManga: (sourceId: string, mangaId: string) => typedError<string[], CommandError>(__TAURI_INVOKE("read_chapters_for_manga", { sourceId, mangaId })),
	readCount: (sourceId: string, mangaId: string) => typedError<number, CommandError>(__TAURI_INVOKE("read_count", { sourceId, mangaId })),
	updateProgress: (sourceId: string, mangaId: string, chapterId: string, page: number, chapterDone: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("update_progress", { sourceId, mangaId, chapterId, page, chapterDone })),
	getProgress: (sourceId: string, mangaId: string) => typedError<{
	source_id: string,
	manga_id: string,
	last_chapter_id: string,
	last_page: number,
	last_chapter_done: boolean,
	updated_at: string,
} | null, CommandError>(__TAURI_INVOKE("get_progress", { sourceId, mangaId })),
	finishChapter: (sourceId: string, mangaId: string, chapterId: string, lastPage: number) => typedError<null, CommandError>(__TAURI_INVOKE("finish_chapter", { sourceId, mangaId, chapterId, lastPage })),
	listSources: () => typedError<SourceInfo[], CommandError>(__TAURI_INVOKE("list_sources")),
	sourceFilters: (sourceId: string) => typedError<Filter[], CommandError>(__TAURI_INVOKE("source_filters", { sourceId })),
	sourceHomepage: (sourceId: string) => typedError<Homepage, CommandError>(__TAURI_INVOKE("source_homepage", { sourceId })),
	sourceSearch: (sourceId: string, query: SearchQuery) => typedError<MangaPage, CommandError>(__TAURI_INVOKE("source_search", { sourceId, query })),
	sourceSection: (sourceId: string, section: SectionRef) => typedError<MangaPage, CommandError>(__TAURI_INVOKE("source_section", { sourceId, section })),
	sourceManga: (sourceId: string, mangaId: string) => typedError<Manga, CommandError>(__TAURI_INVOKE("source_manga", { sourceId, mangaId })),
	sourceChapters: (sourceId: string, mangaId: string) => typedError<Chapter[], CommandError>(__TAURI_INVOKE("source_chapters", { sourceId, mangaId })),
	sourcePages: (sourceId: string, mangaId: string, chapterId: string) => typedError<Page[], CommandError>(__TAURI_INVOKE("source_pages", { sourceId, mangaId, chapterId })),
	installExtension: (wasmPath: string) => typedError<string, CommandError>(__TAURI_INVOKE("install_extension", { wasmPath })),
	/**
	 *  Opens the source's challenge page in a browser window and waits for the user
	 *  to clear it.
	 * 
	 *  Returns true once every cookie the source named has appeared and been copied
	 *  into the shared jar, false on timeout or if the window was closed first.
	 * 
	 *  A separate window rather than one embedded in the app: on Linux wry packs a
	 *  child webview into the window's GtkBox, which ignores the bounds it is given
	 *  and lays the view out as a sibling of the app — so the embedded shape cannot
	 *  be built there at all.
	 */
	solveChallenge: (sourceId: string) => typedError<ChallengeOutcome, CommandError>(__TAURI_INVOKE("solve_challenge", { sourceId })),
	/**
	 *  Closes the challenge window without waiting for it to be solved. The pending
	 *  `solve_challenge` call notices on its next poll and resolves false.
	 */
	cancelChallenge: () => typedError<null, CommandError>(__TAURI_INVOKE("cancel_challenge")),
	getSettings: () => typedError<Settings, CommandError>(__TAURI_INVOKE("get_settings")),
	saveSettings: (newSettings: Settings) => typedError<null, CommandError>(__TAURI_INVOKE("save_settings", { newSettings })),
	effectiveReaderSettings: (sourceId: string, mangaId: string) => typedError<ReaderSettings, CommandError>(__TAURI_INVOKE("effective_reader_settings", { sourceId, mangaId })),
	getSourceReaderOverride: (sourceId: string) => typedError<ReaderOverride, CommandError>(__TAURI_INVOKE("get_source_reader_override", { sourceId })),
	setSourceReaderOverride: (sourceId: string, over: ReaderOverride) => typedError<null, CommandError>(__TAURI_INVOKE("set_source_reader_override", { sourceId, over })),
	getMangaReaderOverride: (sourceId: string, mangaId: string) => typedError<ReaderOverride, CommandError>(__TAURI_INVOKE("get_manga_reader_override", { sourceId, mangaId })),
	setMangaReaderOverride: (sourceId: string, mangaId: string, over: ReaderOverride) => typedError<null, CommandError>(__TAURI_INVOKE("set_manga_reader_override", { sourceId, mangaId, over })),
	listExtensions: () => typedError<InstalledExtension[], CommandError>(__TAURI_INVOKE("list_extensions")),
	uninstallExtension: (extensionId: string) => typedError<null, CommandError>(__TAURI_INVOKE("uninstall_extension", { extensionId })),
	listSourcesWithPreferences: () => typedError<SourceWithPreference[], CommandError>(__TAURI_INVOKE("list_sources_with_preferences")),
	setSourcePreference: (preference: SourcePreference) => typedError<null, CommandError>(__TAURI_INVOKE("set_source_preference", { preference })),
	getSourceSettings: (sourceId: string) => typedError<SourceSettings, CommandError>(__TAURI_INVOKE("get_source_settings", { sourceId })),
	saveSourceSettings: (sourceId: string, values: { [key in string]: string }) => typedError<null, CommandError>(__TAURI_INVOKE("save_source_settings", { sourceId, values })),
	listRepositories: () => typedError<Repository[], CommandError>(__TAURI_INVOKE("list_repositories")),
	addRepository: (url: string) => typedError<RepositoryIndex, CommandError>(__TAURI_INVOKE("add_repository", { url })),
	removeRepository: (url: string) => typedError<null, CommandError>(__TAURI_INVOKE("remove_repository", { url })),
	/**
	 *  Fetches every repository, reporting per-repository failures in the row
	 *  rather than as an error, so one unreachable link does not blank the list.
	 */
	browseRepositories: () => typedError<RepositoryCatalog[], CommandError>(__TAURI_INVOKE("browse_repositories")),
	/**
	 *  Takes the extension's id rather than a download URL so the app only ever
	 *  fetches a binary a registered repository's own index points at — the
	 *  frontend cannot name an arbitrary URL to install from.
	 */
	installFromRepository: (url: string, extensionId: string) => typedError<string, CommandError>(__TAURI_INVOKE("install_from_repository", { url, extensionId })),
	queueDownloads: (sourceId: string, mangaId: string, mangaTitle: string, targets: DownloadTarget[]) => typedError<null, CommandError>(__TAURI_INVOKE("queue_downloads", { sourceId, mangaId, mangaTitle, targets })),
	setDownloadsPaused: (paused: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_downloads_paused", { paused })),
	downloadsPaused: () => typedError<boolean, CommandError>(__TAURI_INVOKE("downloads_paused")),
	cancelDownload: (sourceId: string, mangaId: string, chapterId: string) => typedError<null, CommandError>(__TAURI_INVOKE("cancel_download", { sourceId, mangaId, chapterId })),
	cancelAllDownloads: () => typedError<null, CommandError>(__TAURI_INVOKE("cancel_all_downloads")),
	downloadedChapterIds: (sourceId: string, mangaId: string) => typedError<string[], CommandError>(__TAURI_INVOKE("downloaded_chapter_ids", { sourceId, mangaId })),
	localPages: (sourceId: string, mangaId: string, chapterId: string) => typedError<Page[], CommandError>(__TAURI_INVOKE("local_pages", { sourceId, mangaId, chapterId })),
	deleteDownload: (sourceId: string, mangaId: string, chapterId: string) => typedError<null, CommandError>(__TAURI_INVOKE("delete_download", { sourceId, mangaId, chapterId })),
	listDownloads: () => typedError<DownloadedManga[], CommandError>(__TAURI_INVOKE("list_downloads")),
	exportBackup: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("export_backup", { path })),
	importBackup: (path: string, mode: ImportMode) => typedError<ImportReport, CommandError>(__TAURI_INVOKE("import_backup", { path, mode })),
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	syncStatus: () => typedError<SyncStatus, CommandError>(__TAURI_INVOKE("sync_status")),
	setSyncFolder: (path: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_sync_folder", { path })),
	syncPush: () => typedError<SyncStatus, CommandError>(__TAURI_INVOKE("sync_push")),
	syncPull: () => typedError<ImportReport, CommandError>(__TAURI_INVOKE("sync_pull")),
	setSyncHooks: (postPush: string | null, prePull: string | null) => typedError<null, CommandError>(__TAURI_INVOKE("set_sync_hooks", { postPush, prePull })),
	debugState: () => typedError<DebugState, CommandError>(__TAURI_INVOKE("debug_state")),
	debugTable: (name: string, page: number) => typedError<TablePage, CommandError>(__TAURI_INVOKE("debug_table", { name, page })),
	callLog: () => typedError<CallLogState, CommandError>(__TAURI_INVOKE("call_log")),
	setCallRecording: (on: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("set_call_recording", { on })),
	clearCallLog: () => typedError<null, CommandError>(__TAURI_INVOKE("clear_call_log")),
	exportCallLog: (path: string) => typedError<null, CommandError>(__TAURI_INVOKE("export_call_log", { path })),
	exportTableRows: (path: string, table: string, columns: string[], rows: ((string | null)[])[]) => typedError<null, CommandError>(__TAURI_INVOKE("export_table_rows", { path, table, columns, rows })),
	imageCacheStats: () => typedError<ImageCacheStats, CommandError>(__TAURI_INVOKE("image_cache_stats")),
	clearImageCache: () => typedError<null, CommandError>(__TAURI_INVOKE("clear_image_cache")),
	takeStartupWarnings: () => typedError<StartupWarning[], CommandError>(__TAURI_INVOKE("take_startup_warnings")),
};

/** Events */
export const events = {
	downloadProgress: makeEvent<DownloadProgress>("download-progress"),
	libraryRefreshProgress: makeEvent<LibraryRefreshProgress>("library-refresh-progress"),
};

/* Types */
export type AppearanceSettings = {
	theme?: Theme,
	dark_mode?: ThemeDarkMode,
	show_titles?: boolean,
	compact_mode?: boolean,
	cover_style?: CoverStyle,
	card_size?: CardSize,
	library_layout?: LibraryLayout,
	show_unread_badge?: boolean,
};

export type CallEntry = {
	source_id: string,
	method: string,
	url: string,
	status: number | null,
	error: string | null,
	duration_ms: number | null,
	at: string,
	request_headers: ([string, string])[],
	response_headers: ([string, string])[],
	body: string,
	body_bytes: number | null,
	truncated: boolean,
};

export type CallLogState = {
	recording: boolean,
	entries: CallEntry[],
};

export type CardSize = "Small" | "Medium" | "Large";

export type Category = {
	id: string,
	name: string,
	sort_order: number,
	hidden: boolean,
	locked: boolean,
	is_default: boolean,
	sort_mode: CategorySort,
	color: string | null,
	icon: string | null,
};

export type CategoryCount = {
	category_id: string,
	count: number,
};

export type CategoryFilter = { type: "All" } | { type: "Uncategorized" } | { type: "Category"; id: string };

/**  How long unlocking a locked category keeps it open. */
export type CategoryLockSession = "UntilAppCloses" | "UntilLeave" | "IdleTimeout";

export type CategoryOptions = {
	hidden: boolean,
	locked: boolean,
	is_default: boolean,
	sort_mode: CategorySort,
	color: string | null,
	icon: string | null,
};

export type CategorySort = "added" | "title" | "unread";

/**
 *  An interstitial the user has to clear in a real browser before the source
 *  answers — Cloudflare's managed challenge being the case this exists for.
 */
export type Challenge = {
	/**
	 *  Page to open. Not necessarily `base_url`: the challenge is often
	 *  route-scoped, so this should be one of the routes that actually 403s.
	 */
	url: string,
	/**
	 *  Cookies to harvest once the challenge clears, e.g. `cf_clearance`. They
	 *  are HttpOnly, so nothing script-side can read them back.
	 */
	cookies: string[],
};

/**
 *  What the attempt actually saw. `solved` alone cannot distinguish "the user
 *  walked away" from "the cookie store never answered" from "the site never
 *  issued a clearance", and those want different fixes.
 */
export type ChallengeOutcome = {
	solved: boolean,
	/**  Cookie names present on the last successful read, whatever they were. */
	seen: string[],
	/**  How many times the store answered at all. */
	reads: number,
	/**  Last read failure, if any. */
	error: string | null,
	/**  Where the page ended up, in case it is not where it was sent. */
	landed: string,
};

export type Chapter = {
	id: string,
	title: string,
	manga_id: string,
	number: number | null,
	volume: number | null,
	language: string,
	upload_date: string,
	page_count: number | null,
	scanlator: string | null,
	url: string,
	is_locked: boolean,
};

export type CommandError = { kind: "Source"; detail: {
	source_id: string | null,
	message: string,
} } | { kind: "Extension"; detail: {
	message: string,
} } | { kind: "Database"; detail: {
	message: string,
} } | { kind: "MangaNotCached"; detail: {
	source_id: string,
	manga_id: string,
} } | { kind: "Io"; detail: {
	message: string,
} } | { kind: "Internal"; detail: {
	message: string,
} };

export type ContinueReadingItem = {
	source_id: string,
	manga_id: string,
	title: string,
	cover_url: string,
	last_chapter_id: string,
	last_page: number,
	last_chapter_done: boolean,
	updated_at: string,
};

export type CoverStyle = "Default" | "Rounded" | "Border" | "Shadow";

export type DebugExtension = {
	id: string,
	version: string,
	abi_version: number,
	sources: string[],
};

export type DebugPath = {
	name: string,
	path: string,
	exists: boolean,
};

export type DebugState = {
	app_version: string,
	abi_version: number,
	device_name: string,
	paths: DebugPath[],
	extensions: DebugExtension[],
	image_cache: ImageCacheStats,
	tables: TableCount[],
	settings: Settings,
};

export type DownloadProgress = {
	source_id: string,
	manga_id: string,
	manga_title: string,
	chapter_id: string,
	title: string,
	state: DownloadState,
	done: number,
	total: number,
	error: string | null,
};

export type DownloadState = "Queued" | "Downloading" | "Done" | "Failed" | "Cancelled";

export type DownloadTarget = {
	chapter_id: string,
	title: string,
};

export type DownloadedChapter = {
	source_id: string,
	manga_id: string,
	chapter_id: string,
	title: string,
	page_count: number,
	total_bytes: number | null,
	downloaded_at: string,
};

export type DownloadedManga = {
	source_id: string,
	manga_id: string,
	title: string,
	cover_url: string,
	total_bytes: number | null,
	chapters: DownloadedChapter[],
};

export type EntryRef = {
	source_id: string,
	manga_id: string,
};

export type ExtensionInfo = {
	id: string,
	name: string,
	version: string,
	abi_version: number,
	author: string,
	website: string | null,
};

export type ExtensionRef = {
	id: string,
	version: string,
};

/**
 *  A filter a source exposes on its search screen. Every variant is keyed by an
 *  `id` that ties it to the [`FilterValue`] the user sends back.
 * 
 *  Prefer the constructors ([`Filter::select`], [`Filter::sort`], …) over the
 *  struct literal form; they fill in the optional fields and read more clearly
 *  when a source declares many filters at once.
 */
export type Filter = 
/**  A free-text field. */
{ type: "Text"; id: string; label: string; placeholder: string | null } | 
/**  An on/off switch. */
{ type: "Toggle"; id: string; label: string; default: boolean } | 
/**  Pick exactly one option. */
{ type: "Select"; id: string; label: string; options: SelectOption[]; default: string | null } | 
/**
 *  Pick any number of options; may also allow excluding them when
 *  `supports_exclusion` is set (e.g. include/exclude tags).
 */
{ type: "MultiSelect"; id: string; label: string; options: SelectOption[]; supports_exclusion: boolean } | 
/**  A sort key, optionally reversible when `can_reverse` is set. */
{ type: "Sort"; id: string; label: string; options: SelectOption[]; default: string | null; can_reverse: boolean };

/**
 *  A user's selection for one [`Filter`], carrying the same `id`. Read these off
 *  a search with the [`FilterValues`] trait rather than matching by hand.
 */
export type FilterValue = { type: "Text"; id: string; value: string } | { type: "Toggle"; id: string; value: boolean } | { type: "Select"; id: string; value: string } | { type: "MultiSelect"; id: string; included: string[]; excluded: string[] } | { type: "Sort"; id: string; value: string; reversed: boolean };

export type HistoryEntryRef = {
	source_id: string,
	manga_id: string,
};

export type Homepage = {
	sections: HomepageSection[],
};

export type HomepageSection = {
	id: string,
	title: string,
	layout: SectionLayout,
	items: MangaSimple[],
	paginable: boolean,
};

export type ImageCacheLimit = "Off" | "Mb256" | "Mb512" | "Gb1" | "Gb2";

export type ImageCacheStats = {
	file_count: number,
	total_bytes: number | null,
};

export type ImportMode = "Merge" | "Replace";

export type ImportReport = {
	entries: number,
	categories: number,
	read_chapters: number,
	progress: number,
	missing_extensions: ExtensionRef[],
};

export type InstalledExtension = {
	info: ExtensionInfo,
	sources: SourceInfo[],
};

export type LibraryItem = {
	source_id: string,
	manga_id: string,
	title: string,
	cover_url: string,
	added_at: string,
	cached_total_chapters: number,
	read_chapters: number,
};

export type LibraryLayout = "Grid" | "List";

/**
 *  Emitted once per series while a library refresh runs, so the UI can show a
 *  determinate progress bar. A final event with `done == total` marks the end.
 */
export type LibraryRefreshProgress = {
	done: number,
	total: number,
	current_title: string,
};

export type LibrarySearch = {
	field: LibrarySearchField,
	query: string,
};

export type LibrarySearchField = "title" | "author" | "artist" | "tag" | "description";

export type LibraryUpdate = {
	source_id: string,
	manga_id: string,
	title: string,
	cover_url: string,
	new_count: number,
	latest_chapter_id: string,
	latest_chapter_title: string,
	latest_number: number | null,
	found_at: string,
};

export type Manga = {
	id: string,
	title: string,
	description: string,
	tags: Tag[],
	cover_url: string,
	author: string[],
	artist: string[],
	status: Status,
	last_updated: string,
	rating: number | null,
	views: bigint,
};

export type MangaPage = {
	items: MangaSimple[],
	has_next: boolean,
};

export type MangaSimple = {
	id: string,
	title: string,
	description: string | null,
	cover_url: string,
};

export type Page = {
	number: number,
	image_url: string,
};

export type PageLayout = "SinglePage" | "DoublePage" | "VerticalScroll";

export type ReadProgress = {
	source_id: string,
	manga_id: string,
	last_chapter_id: string,
	last_page: number,
	last_chapter_done: boolean,
	updated_at: string,
};

export type ReaderOverride = {
	page_layout?: PageLayout | null,
	zoom_behavior?: ZoomBehavior | null,
	reading_direction?: ReadingDirection | null,
};

export type ReaderSettings = {
	page_layout?: PageLayout,
	zoom_behavior?: ZoomBehavior,
	reading_direction?: ReadingDirection,
	zoom_level?: number | null,
	remember_zoom?: boolean,
};

export type ReadingDirection = "LeftToRight" | "RightToLeft";

export type RefreshScope = { type: "All" } | { type: "Category"; id: string } | { type: "Entries"; entries: EntryRef[] };

export type RefreshSummary = {
	checked: number,
	new_chapters: number,
};

export type Repository = {
	url: string,
	name: string,
	added_at: string,
	last_fetched_at: string | null,
};

export type RepositoryCatalog = {
	repository: Repository,
	index: RepositoryIndex | null,
	error: string | null,
	/**
	 *  Ids from this index whose ABI this app cannot load, resolved here so the
	 *  frontend never has to carry a copy of the supported range.
	 */
	unsupported: string[],
};

export type RepositoryExtension = {
	info: ExtensionInfo,
	download_url: string,
	sources: SourceInfo[],
};

export type RepositoryIndex = {
	index_version: number,
	name: string,
	description?: string | null,
	website?: string | null,
	extensions: RepositoryExtension[],
};

export type SearchQuery = {
	term: string,
	page: number,
	filters?: FilterValue[],
};

export type SectionLayout = "SingleRow" | "DoubleRow" | "TripleRow" | "FeaturedRow";

export type SectionRef = {
	section_id: string,
	page: number,
};

/**
 *  One choice in a `Select`, `MultiSelect`, or `Sort` filter (and in the
 *  equivalent [`crate::extension::config::Setting`] kinds).
 * 
 *  `id` is the stable value sent back on selection; `label` is what the user
 *  sees. Build several at once with [`SelectOption::list`].
 */
export type SelectOption = {
	id: string,
	label: string,
};

export type Setting = {
	id: string,
	label: string,
	description: string | null,
	kind: SettingKind,
};

export type SettingKind = { type: "Text"; secret: boolean; placeholder: string | null; default: string | null } | { type: "Toggle"; default: boolean } | { type: "Select"; options: SelectOption[]; default: string | null } | { type: "MultiSelect"; options: SelectOption[]; default: string[] } | { type: "TextList"; placeholder: string | null; default: string[] } | { type: "Number"; min: number | null; max: number | null; default: number | null };

export type Settings = {
	appearance?: AppearanceSettings,
	reader?: ReaderSettings,
	sidebar?: SidebarSettings,
	system?: SystemSettings,
};

export type SidebarSettings = {
	pinned_sources?: string[],
};

export type SourceInfo = {
	id: string,
	name: string,
	version: string,
	language: string,
	base_url: string,
	icon_url: string | null,
	hosts: string[],
	nsfw: boolean,
	challenge?: Challenge | null,
};

export type SourcePreference = {
	source_id: string,
	enabled: boolean,
	private: boolean,
	blur_covers: boolean,
	skip_updates: boolean,
	default_category_id: string | null,
};

export type SourceSettings = {
	schema: Setting[],
	values: { [key in string]: string },
};

export type SourceWithPreference = {
	info: SourceInfo,
	preference: SourcePreference,
};

export type StartupWarning = {
	kind: WarningKind,
	message: string,
};

export type Status = "Ongoing" | "Completed" | "Hiatus" | "Cancelled" | "Unknown";

export type SyncStatus = {
	folder: string | null,
	device_name: string,
	remote_device_name: string | null,
	remote_created_at: string | null,
	remote_is_this_device: boolean,
	local_activity_at: string | null,
	last_push_at: string | null,
	last_pull_at: string | null,
	/**
	 *  True when this device has read or added something after the snapshot in
	 *  the folder was taken — pulling would discard it.
	 */
	local_changes_since_remote: boolean,
	post_push_command: string | null,
	pre_pull_command: string | null,
};

export type SystemSettings = {
	update_on_startup?: boolean,
	background_updates?: UpdateInterval,
	check_library_on_start?: boolean,
	confirm_removal?: boolean,
	enable_notifications?: boolean,
	image_cache_limit?: ImageCacheLimit,
	category_lock_session?: CategoryLockSession,
	category_lock_idle_minutes?: number,
	developer_mode?: boolean,
};

export type TableCount = {
	name: string,
	rows: number | null,
};

export type TablePage = {
	name: string,
	columns: string[],
	rows: ((string | null)[])[],
	total: number | null,
	page: number,
	page_size: number,
};

export type Tag = {
	id: string,
	label: string,
};

export type Theme = "Default" | "Void" | "Havoc" | "Amber" | "Rose" | "Cyberpunk";

export type ThemeDarkMode = "System" | "Light" | "Dark";

export type UpdateInterval = "Off" | "Every6Hours" | "Every12Hours" | "Every24Hours";

export type WarningKind = "SettingsCorrupt" | "ExtensionFailed";

export type ZoomBehavior = "FitWidth" | "FitHeight" | "ActualSize" | "Manual";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

