/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppHistoryRouteImport } from './routes/_app/history'
import { Route as AppLibraryRouteImport } from './routes/_app/library'
import { Route as AppBrowseIndexRouteImport } from './routes/_app/browse/index'
import { Route as AppBrowseSourceIdRouteImport } from './routes/_app/browse/$sourceId'
import { Route as AppMangaSourceIdMangaIdRouteImport } from './routes/_app/manga.$sourceId.$mangaId'
import { Route as ReadSourceIdMangaIdChapterIdRouteImport } from './routes/read.$sourceId.$mangaId.$chapterId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseIndexRoute = AppBrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => AppRoute,
} as any)
const AppBrowseSourceIdRoute = AppBrowseSourceIdRouteImport.update({
  id: '/browse/$sourceId',
  path: '/browse/$sourceId',
  getParentRoute: () => AppRoute,
} as any)
const AppMangaSourceIdMangaIdRoute = AppMangaSourceIdMangaIdRouteImport.update({
  id: '/manga/$sourceId/$mangaId',
  path: '/manga/$sourceId/$mangaId',
  getParentRoute: () => AppRoute,
} as any)
const ReadSourceIdMangaIdChapterIdRoute =
  ReadSourceIdMangaIdChapterIdRouteImport.update({
    id: '/read/$sourceId/$mangaId/$chapterId',
    path: '/read/$sourceId/$mangaId/$chapterId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/history': typeof AppHistoryRoute
  '/library': typeof AppLibraryRoute
  '/browse/$sourceId': typeof AppBrowseSourceIdRoute
  '/browse/': typeof AppBrowseIndexRoute
  '/manga/$sourceId/$mangaId': typeof AppMangaSourceIdMangaIdRoute
  '/read/$sourceId/$mangaId/$chapterId': typeof ReadSourceIdMangaIdChapterIdRoute
}
export interface FileRoutesByTo {
  '/history': typeof AppHistoryRoute
  '/library': typeof AppLibraryRoute
  '/': typeof AppIndexRoute
  '/browse/$sourceId': typeof AppBrowseSourceIdRoute
  '/browse': typeof AppBrowseIndexRoute
  '/manga/$sourceId/$mangaId': typeof AppMangaSourceIdMangaIdRoute
  '/read/$sourceId/$mangaId/$chapterId': typeof ReadSourceIdMangaIdChapterIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/history': typeof AppHistoryRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/': typeof AppIndexRoute
  '/_app/browse/$sourceId': typeof AppBrowseSourceIdRoute
  '/_app/browse/': typeof AppBrowseIndexRoute
  '/_app/manga/$sourceId/$mangaId': typeof AppMangaSourceIdMangaIdRoute
  '/read/$sourceId/$mangaId/$chapterId': typeof ReadSourceIdMangaIdChapterIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/library'
    | '/browse/$sourceId'
    | '/browse/'
    | '/manga/$sourceId/$mangaId'
    | '/read/$sourceId/$mangaId/$chapterId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/history'
    | '/library'
    | '/'
    | '/browse/$sourceId'
    | '/browse'
    | '/manga/$sourceId/$mangaId'
    | '/read/$sourceId/$mangaId/$chapterId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/history'
    | '/_app/library'
    | '/_app/'
    | '/_app/browse/$sourceId'
    | '/_app/browse/'
    | '/_app/manga/$sourceId/$mangaId'
    | '/read/$sourceId/$mangaId/$chapterId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ReadSourceIdMangaIdChapterIdRoute: typeof ReadSourceIdMangaIdChapterIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/history': {
      id: '/_app/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/': {
      id: '/_app/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof AppBrowseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/browse/$sourceId': {
      id: '/_app/browse/$sourceId'
      path: '/browse/$sourceId'
      fullPath: '/browse/$sourceId'
      preLoaderRoute: typeof AppBrowseSourceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/manga/$sourceId/$mangaId': {
      id: '/_app/manga/$sourceId/$mangaId'
      path: '/manga/$sourceId/$mangaId'
      fullPath: '/manga/$sourceId/$mangaId'
      preLoaderRoute: typeof AppMangaSourceIdMangaIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/read/$sourceId/$mangaId/$chapterId': {
      id: '/read/$sourceId/$mangaId/$chapterId'
      path: '/read/$sourceId/$mangaId/$chapterId'
      fullPath: '/read/$sourceId/$mangaId/$chapterId'
      preLoaderRoute: typeof ReadSourceIdMangaIdChapterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppHistoryRoute: typeof AppHistoryRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppIndexRoute: typeof AppIndexRoute
  AppBrowseSourceIdRoute: typeof AppBrowseSourceIdRoute
  AppBrowseIndexRoute: typeof AppBrowseIndexRoute
  AppMangaSourceIdMangaIdRoute: typeof AppMangaSourceIdMangaIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHistoryRoute: AppHistoryRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppIndexRoute: AppIndexRoute,
  AppBrowseSourceIdRoute: AppBrowseSourceIdRoute,
  AppBrowseIndexRoute: AppBrowseIndexRoute,
  AppMangaSourceIdMangaIdRoute: AppMangaSourceIdMangaIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ReadSourceIdMangaIdChapterIdRoute: ReadSourceIdMangaIdChapterIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
